// Downloads the Latin subsets of the site fonts into public/fonts/ and writes
// src/fonts.css. Run it again after changing families or weights:
//
//   node scripts/fetch-fonts.mjs
//
// Self-hosting avoids a render-blocking request to the Google Fonts CDN and
// keeps visitor IP addresses off a third-party service, which matters for an
// audience in Switzerland and the EU.

import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = join(root, "public", "fonts");

// Weight ranges rather than discrete weights: Google then serves one variable
// font file per subset instead of one static file per weight, which is far
// lighter (four Inter weights cost 188 kB as statics, ~50 kB as one variable).
const API =
  "https://fonts.googleapis.com/css2?family=Syne:wght@600..800" +
  "&family=Inter:wght@300..700" +
  "&family=JetBrains+Mono:wght@400..500&display=swap";

// A modern browser UA is required for Google to serve woff2 rather than ttf.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const css = await fetch(API, { headers: { "User-Agent": UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts returned ${r.status}`);
  return r.text();
});

const faces = [];
const re = /\/\* ([a-z-]+) \*\/\s*@font-face \{([^}]+)\}/g;
let m;
while ((m = re.exec(css)) !== null) {
  const [, subset, body] = m;
  // The site is French and English only: skip Cyrillic, Greek and Vietnamese.
  if (subset !== "latin" && subset !== "latin-ext") continue;

  const family = body.match(/font-family:\s*'([^']+)'/)[1];
  // Variable fonts declare a range ("300 600"), static ones a single value.
  const weight = body.match(/font-weight:\s*([\d\s]+?);/)[1].trim();
  const url = body.match(/url\((https:[^)]+)\)/)[1];
  const range = body.match(/unicode-range:\s*([^;]+);/)[1].trim();
  const slug = weight.replace(/\s+/g, "-");
  const file = `${family.toLowerCase().replace(/\s+/g, "-")}-${slug}-${subset}.woff2`;

  faces.push({ family, weight, url, range, file });
}

if (faces.length === 0) throw new Error("no latin faces found in the Google Fonts response");

mkdirSync(fontsDir, { recursive: true });

let bytes = 0;
for (const face of faces) {
  const buf = Buffer.from(await fetch(face.url).then((r) => r.arrayBuffer()));
  writeFileSync(join(fontsDir, face.file), buf);
  bytes += buf.length;
}

const rules = faces
  .map(
    (f) => `@font-face {
  font-family: "${f.family}";
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url("/fonts/${f.file}") format("woff2");
  unicode-range: ${f.range};
}`,
  )
  .join("\n\n");

writeFileSync(
  join(root, "src", "fonts.css"),
  `/*
 * Generated by scripts/fetch-fonts.mjs. Do not edit by hand.
 * Self-hosted Latin subsets of Syne, Inter and JetBrains Mono.
 */

${rules}
`,
);

console.log(`${faces.length} font files, ${(bytes / 1024).toFixed(0)} kB total`);
console.log("wrote src/fonts.css");
